
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
CardGame = { path = "../game", default-features = false }

[features]
default = ["CardGame/default"]
dylib-engine = ["CardGame/dylib-engine"]
